### ISSUE TITLE
JSON flattening + passing decoders as arguments 

### ISSUE THREAD

**Issue by alex35mil** [glennsl/rescript-json-combinators#4]
Let's say there is a JSON input of the following shape:

```json
{
    "id": string,
    "data": {
        "name": string,
        "position": int,
        ... variable set of properties ...
    }
}
```

The target record type looks like this:

```rescript
type t = {
    id: string,
    name: string,
    position: int,
    metadata: Metadata.t,
}
```

The inner content of metadata is variable depending on the request parameters. I need to use different decoders (depending on the usage context) to construct it.

I want to write a general decoder that takes a metadata decoder (maps JSON under the `data` key to the `Metadata.t`) as input:

```rescript
let decode = metadataDecoder => { ... }
```

Also, I want to be able to use field decoders (`field.required`/`field.optional`) to handle missing keys / invalid types at keys properly.

What would be the optimal way to implement this?

**Comment by glennsl** [comment]
Hi. Sorry for the late reply. I believe an `andThen` combinator would be needed for this. It hasn't been added to this library yet, but see the documentation in `bs-json` for [an example of its use](https://github.com/glennsl/bs-json/blob/47ad1febb7c0d52dac2964e1dd4cdff63508b4b4/src/Json_decode.mli#L441-L495). It should be quite trivial to add.

**Comment by glennsl** [comment]
Added `flatMap`, which should solve this.

**Comment by alex35mil** [comment]
@glennsl Thanks! I worked around it somehow back then, but it wasn't pretty lol
