### ISSUE TITLE
Null handling?

### ISSUE THREAD

**Issue by suzdalnitski** [glennsl/rescript-json-combinators#5]
Hi,

It seems that `null` values in Json can't be parsed. Eg the following fails:

```rescript
`
{
    "errors": [
        {
            "extensions": {
                "code": "unauthenticated",
                "reference": null
            },
            "message": "You must be authenticated to perform this action",
            "path": [ "startPlanCheckout" ]
        }
    ]
}
`
->Js.Json.parseExn
->JsonCombinators.Json.decode(DecodeErrors.fetchResult)
```

My decoder is:
```rescript
module DecodeErrors = {
  open JsonCombinators.Json.Decode

  type extensions = {
    code: string,
    reference: option<string>,
  }

  type error = {
    message: string,
    path: array<string>,
    extensions: extensions,
  }

  type fetchResult = {errors: option<array<error>>}

  let errorField = object(field => {
    message: field.required(. "message", string),
    path: field.required(. "path", array(string)),
    extensions: field.required(.
      "extensions",
      object(field => {
        code: field.required(. "code", string),
        reference: field.optional(. "reference", string),
      }),
    ),
  })

  let fetchResult = object(field => {
    errors: field.optional(. "errors", array(errorField)),
  })
}
```

This results in the following error: `Expected string, got null\n\tat field 'reference'\n\ta…tensions'\n\tin array at index 0\n\tat field 'errors'`

It seems that `optional` doesn`t support nulls (which makes sense since `None` is compiled to `undefined` in Rescript).

Is there a way to make `nulls` also be treated as optional?

Thanks!

**Comment by glennsl** [comment]
That's what `option` is for. Try:

```
reference: field.required(. "reference", option(string)),
```

If `optional` also accepted `null` you wouldn't be able to distinguish between the field being null and not being present at all.

**Comment by suzdalnitski** [comment]
Yup, this works for `null`!

However, this fails with `undefined` values (as expected).

Is there a way to make this work with both `null` and `undefined`? Something similar to `Js.Nullable.t`? I don't think I ever had a use case, where I had to distinguish between the two.

Thanks!

**Comment by glennsl** [comment]
This should work:

```
reference: field.optional(. "reference", option(string))->Belt.Option.flatMap(x => x),
```

Eventually you'll be able to use `Option.flat` from `rescript-core`.

**Comment by suzdalnitski** [comment]
That makes sense, thank you!
